[package]
name = "crypto"
version = "0.0.3"
edition = "2021"

[dependencies]
wchar = "^0.11"
winapi = { version = "^0.3.7", features = ["consoleapi", "libloaderapi"] }
libc = "^0.2.107"
base64 = "^0.13.0"
hex = "^0.4.3"
aes = "^0.7.5"
block-modes = "^0.8.1"
digest = "^0.9.0"
sha2 = "^0.9.8"
md-5 = "^0.9.1"
md4 = "^0.9.0"
sha-1 = "^0.9.1"
sha3 = "^0.9.1"
ripemd160 = "^0.9.1"
ripemd256 = "^0.1.0"
ripemd320 = "^0.9.0"
hmac = {version = "^0.11.0", features = ["std"]}
thiserror = "1.0"
rsa = "^0.5.0"
rand = "^0.8.4"
bcrypt = "^0.10.1"
scrypt = "^0.8.0"
pbkdf2 = {version = "^0.9.0", features = ["simple", "sha1"]}
blowfish = "^0.8.0"
byteorder = "^1.4.3"
mimalloc = { version = "0.1.17" }
arc4 = "0.1.0"

[dev-dependencies]
criterion = "0.3"
libloading = "0.7.2"
timeit = "0.1.2"

[[bench]]
name = "hash_benchmark"
harness = false

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = 'abort'