[package]
name = "crypto"
version = "0.0.1"
edition = "2021"

[dependencies]
wchar = "^0.11"
winapi = { version = "^0.3.7", features = ["consoleapi", "libloaderapi"] }
libc = "^0.2.107"
base64 = "^0.13.0"
hex = "^0.4.3"
aes = "^0.7.5"
block-modes = "^0.8.1"


[lib]
crate-type = ["cdylib"]

[profile.release]
panic = 'abort'